#pragma once
// Artifact Fabric - version information
#define ARTIFACT_FABRIC_VERSION_MAJOR 1
#define ARTIFACT_FABRIC_VERSION_MINOR 0
#define ARTIFACT_FABRIC_VERSION_PATCH 0
#define ARTIFACT_FABRIC_VERSION_STRING "1.0.0"
#define ARTIFACT_FABRIC_PROTOCOL_VERSION 1
